### ISSUE TITLE
What is the reason for the author's error and how can I avoid it

### ISSUE THREAD

**Issue by yxl23** [geekan/MetaGPT#1154] opened 2024-04-02 05:33 UTC
![image](https://github.com/geekan/MetaGPT/assets/115678682/3466a6b8-f9ff-41f7-bd85-68304e1a8baf)
![image](https://github.com/geekan/MetaGPT/assets/115678682/c06459b5-37bd-4ccd-8d2c-de67d56d8861)

**Comment by iorisa** [comment] 2024-04-02 08:20
The reason for the issue is that LLM did not return the data in the required format: the "Programming Language" field is missing.
This problem can only be resolved by improving the performance of LLM, either by changing the model or upgrading its version.

**Closed** 2024-10-10 02:30 UTC
