### ISSUE TITLE
TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'

### ISSUE THREAD

**Issue by gdmcdonald** [geekan/MetaGPT#111] opened 2023-08-04 05:43 UTC
```bash
$ python startup.py "Write a cli snake game based on pygame"
Traceback (most recent call last):
  File "~/metagpt/startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager
  File "~//metagpt/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "~/metagpt/metagpt/roles/role.py", line 12, in <module>
    from pydantic import BaseModel, Field
  File "~/opt/anaconda3/lib/python3.9/site-packages/pydantic-1.10.7-py3.9.egg/pydantic/__init__.py", line 2, in <module>
    from . import dataclasses
  File "~/opt/anaconda3/lib/python3.9/site-packages/pydantic-1.10.7-py3.9.egg/pydantic/dataclasses.py", line 48, in <module>
    from .main import create_model, validate_model
  File "~/opt/anaconda3/lib/python3.9/site-packages/pydantic-1.10.7-py3.9.egg/pydantic/main.py", line 120, in <module>
    @dataclass_transform(kw_only_default=True, field_specifiers=(Field,))
TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'
```

**Comment by geekan** [comment] 2023-08-05 14:17
Caused by pydantic?
Googled and find this: https://github.com/explosion/spaCy/issues/12034

**Comment by better629** [comment] 2024-10-10 06:34
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.

**Closed by better629** 2024-10-10 06:34 UTC
