### ISSUE TITLE
Local model:  Warning: model not found. Using cl100k_base encoding.

### ISSUE THREAD

**Issue by HuntZhaozq** [geekan/MetaGPT#433] opened 2023-10-16 05:56 UTC
I am trying to use openai type local model instead of GPT4.  I change the API_BASE and API_model in key.yaml file. But I meet some problem:

Warning: model not found. Using cl100k_base encoding.
tenacity.RetryError: RetryError[<Future at 0x7f4824da0d90 state=finished raised JSONDecodeError>]

How to solve this problem? And what should I modify the code if I want to use local model.

**Comment by iorisa** [comment] 2023-10-23 02:52
The reason for the issue is that the results returned by the local model did not adhere to the requirements of the prompt, which resulted in this JSONDecodeError.

Considering that the issue has already been resolved in Discord and the WeChat group, I won't provide any further responses here.

**Comment by HuntZhaozq** [comment] 2023-10-23 03:58
Hello, I am not in Discord and Wechat group. Could you please provide some information and responses for me here? Thank you very much!

**Comment by iorisa** [comment] 2023-10-23 07:22
The analysis and troubleshooting for the entire issue involve the following steps:

1. Ensure the local model is functioning correctly. You can use the `curl` command to confirm whether the local model supports the HTTP protocol and is working properly.

2. Ensure that the local model adheres to the openai interface standards. This information can be found on the model's official website. If the model does not support this interface, you may need to develop it yourself. You can refer to the `OpenAIGPTAPI` class in `metagpt/provider/openai_api.py`, inherit from the `BaseGPTAPI` class, and implement the `acompletion_text` function.

3. Once both of the above tests pass, you can begin integrating the local model with MetaGPT.

4. If you've implemented a subclass of `BaseGPTAPI` yourself, you can add `print(self.__class__)` in `_aask_v1` and `_aask` within `metagpt/actions/action.py` to print the name of the class being called.

5. In `_aask_v1` and `_aask` within `metagpt/actions/action.py`, add logging to print the input and output of the local model. This will help you check if the local model's output is compatible with the subsequent workflow.

In a previous case, the issue was due to the local model's output not conforming to the JSON format required by the prompt, which caused an error when parsing JSON in `_aask_v1`.

[MetaGPT Discord](https://discord.gg/uQ6hqVd3)

**Comment by iorisa** [comment] 2023-10-23 07:28
The configurations related to the LLM call are as follows:

OPENAI_API_BASE: "https://api.openai.com/v1"
#OPENAI_PROXY: "http://127.0.0.1:8118"
#OPENAI_API_KEY: "YOUR_API_KEY"
OPENAI_API_MODEL: "gpt-4"

**Comment by HuntZhaozq** [comment] 2023-10-23 07:51
Thank you very much! I try the other local model. It works but the quality of the ouput codes is pretty bad...

**Closed** 2023-10-26 03:03 UTC
