### ISSUE TITLE
event error: [1214][history参数非法。请检查文档。] 

### ISSUE THREAD

**Issue by springasa** [geekan/MetaGPT#725] opened 2024-01-08 15:42 UTC
**Bug description**

在运行examples\search_google.py示例时，出现“event error: [1214][history参数非法。请检查文档。] ”的错误

The error "event error: [1214][history parameter is invalid. Please check the documentation.]" occurred when running the examples\search_google.py .

**Bug solved method**

**Environment information**

- LLM type and model name: ZhiPuAILLM chatglm_turbo 
- System version:win11
- Python version: 3.11.4

- packages version:
- installation method: 

**Screenshots or logs**

```
2024-01-08 22:54:34.334 | INFO     | metagpt.const:get_metagpt_package_root:32 - Package root set to D:\workspace\sourcecode\MetaGPT
2024-01-08 22:54:34.521 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.ZHIPUAI
2024-01-08 22:54:37.764 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.ZHIPUAI
2024-01-08 22:54:37.772 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.ZHIPUAI
2024-01-08 22:54:37.773 | INFO     | metagpt.roles.searcher:_act_sp:60 - Alice(Smart Assistant): to do SearchAndSummarize(SearchAndSummarize)
2024-01-08 22:54:39.616 | ERROR    | metagpt.provider.zhipuai_api:_achat_completion_stream:102 - event error: [1214][history参数非法。请检查文档。]
2024-01-08 22:54:39.617 | INFO     | metagpt.utils.cost_manager:update_cost:48 - Total running cost: $0.000 | Max budget: $10.000 | Current cost: $0.000, prompt_tokens: 0, completion_tokens: 0

```

**Comment by better629** [comment] 2024-01-09 12:19
@springasa can you try the current main branch. https://github.com/geekan/MetaGPT/pull/662/files has fixed the problem which due to ZhiPuAI can't have system_prompt.

**Comment by springasa** [comment] 2024-01-09 15:24
> @springasa can you try the current main branch. https://github.com/geekan/MetaGPT/pull/662/files has fixed the problem which due to ZhiPuAI can't have system_prompt.

The same error still occurs on the main branch.

**Comment by better629** [comment] 2024-01-10 03:16
@springasa ok. the problem is that https://github.com/geekan/MetaGPT/blob/main/metagpt/actions/search_and_summarize.py#L155 add extra `system_prompt` which not consider the llm has system_prompt or not.

there are something you can try  inside `metagpt/actions/search_and_summarize.py`  
move the system prompt into user prompt to keep search effect.

```
SEARCH_AND_SUMMARIZE_SALES_PROMPT = """
{SYSTEM_PROMPT}

## Reference Information
{CONTEXT}

## Dialogue History
{QUERY_HISTORY}
{QUERY}
> {ROLE}: 

"""
```

```
        prompt = SEARCH_AND_SUMMARIZE_PROMPT.format(
            SYSTEM_PROMPT=SEARCH_AND_SUMMARIZE_SYSTEM,
            ROLE=self.prefix,
            CONTEXT=rsp,
            QUERY_HISTORY="\n".join([str(i) for i in context[:-1]]),
            QUERY=str(context[-1]),
        )
        result = await self._aask(prompt)
```

there will be a fix to drop system_prompt if the llm can't support system_prompt.

**Comment by better629** [comment] 2024-01-10 03:31
@springasa fix https://github.com/geekan/MetaGPT/pull/732 has committed.

Due to ZhipuAI will not use system_prompt(SEARCH_AND_SUMMARIZE_SYSTEM), the `SEARCH_AND_SUMMARIZE_PROMPT ` will be drop. Although it can successful. But if you want to get better result, maybe you can add `SEARCH_AND_SUMMARIZE_SYSTEM` inside `SEARCH_AND_SUMMARIZE_PROMPT`.

**Closed** 2024-01-10 03:31 UTC
